version: '1'

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pjKuj1YAbWGu1resLhjr
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressAdmin
      MYSQL_PASSWORD: fhVDcYT9ThAKleLg3sas

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8081:8080"
      - "50000:50000"
    restart: always
    container_name: jenkins
    volumes:
      - /home/root/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  ssh-agent:
    image: jenkins/ssh-agent
  jira:
    image: atlassian/jira-software
    ports:
      - "8080:8080"
    volumes:
     - jiraVolume:/var/atlassian/application-data/jira
volumes:
  jiraVolume:
  jenkins_home:
  db_data: